rewritten to have both interactive and command-line versions

diff --git a/bin/scripts/obuildtree b/bin/scripts/obuildtree
--- a/bin/scripts/obuildtree
+++ b/bin/scripts/obuildtree
@@ -6,29 +6,6 @@
 
 ###########################################################################
 #
-# Unfortunately the built-in "read" doesn't work on NT so we need this.  It
-# also has the beneficial side-effect of expanding environment variables in
-# the input string.
-#
-
-myread() {
-  eval "$1=\"`head -1`\""
-}
-
-
-###########################################################################
-#
-# Check arguments
-#
-
-if [ $# -ne 0 ]; then
-  echo "usage: $0"
-  exit 1
-fi
-
-
-###########################################################################
-#
 # Check that we have GNU make
 #
 
@@ -55,46 +32,275 @@ fi
 
 ###########################################################################
 #
-# Get the base OMNI tree
+# Unfortunately the built-in "read" doesn't work on NT so we need this.  It
+# also expands environment variables in the input string, but this means
+# it doesn't cope with double-quotes the input string.
 #
 
-echo
-echo "Enter the base OMNI tree for this build tree"
-echo -n "> [$OMNI_TREE] "
-
-myread baseomnitree
-
-if [ "$baseomnitree" = "" ]; then
-  baseomnitree="$OMNI_TREE"
-  if [ "$baseomnitree" = "" ]; then
-    exit 1
+myread() {
+  if [ "$2" != "" ]; then
+    echo -n "> [$2] "
+  else
+    echo -n "> "
   fi
-fi
+  result=`head -1`
+  if [ "$result" = "" ]; then
+    result=$2
+  fi
+  eval "$1=\"$result\""
+}
 
 
 ###########################################################################
 #
+# Function to get details interactively:
+#
+
+interactive() {
+
+#
+# Get the base OMNI tree
+#
+
+  echo
+  echo "Enter the base OMNI tree for this build tree"
+  myread baseomnitree $OMNI_TREE
+
+  if [ "$baseomnitree" = "" ]; then
+    echo "Error: no base OMNI tree specified"
+    exit 1
+  fi
+
+
+#
 # Get the platform
 #
 
-echo
-echo "Enter the platform name from:"
-(cd $baseomnitree/mk/platforms; ls *.mk */*.mk | sed s/\.mk//g)
+  getdefaultplatform
+  echo
+  echo "Enter the platform name from:"
+  (cd $baseomnitree/mk/platforms; ls *.mk */*.mk | sed s/\.mk//g)
+  myread platform $defaultplatform
 
-if [ -x /usr/local/bin/arch ]; then
-  defaultplatform=`/usr/local/bin/arch -binv`;
-  if [ ! -e "$baseomnitree/mk/platforms/$defaultplatform.mk" ]; then
-    unset defaultplatform
+  if [ ! -r "$baseomnitree/mk/platforms/$platform.mk" ]; then
+    echo
+    echo "No such platform \"$platform\""
+    echo
+    exit 1
   fi
+
+
+#
+# Get the destination
+#
+
+  echo
+  echo "Enter the destination directory"
+  myread dest $platform
+
+  if [ -e "$dest" ]; then
+    echo "Error: \"$dest\" already exists."
+    exit 1
+  fi
+
+
+#
+# Get the export tree
+#
+
+  echo
+  echo "Does this build tree have an export tree ?"
+  myread hasexporttree y
+
+  if [ "$hasexporttree" = "y" ]; then
+    current=`pwd`
+    if [ `basename $current` = "build" ]; then
+      defaultexporttree=`dirname $current`
+    fi
+
+    echo
+    echo "Enter the export tree"
+    myread exporttree $defaultexporttree
+  fi
+
+
+#
+# Get the import trees
+#
+
+  echo
+
+  if [ "$exporttree" = "$baseomnitree" ]; then
+
+    echo "The only import tree will be $exporttree (this is both"
+    echo "the export tree & the base OMNI tree)"
+    imports="$exporttree"
+
+  else
+
+    if [ "$exporttree" != "" ]; then
+      echo "The first import tree will be $exporttree (the export tree)"
+    fi
+
+    echo "The final import tree will be $baseomnitree (the base OMNI tree)"
+
+    extraenvimports=`echo $OMNI_IMPORT_TREES | tr ' ' '\n' | \
+		     egrep -v '^'$exporttree'$'`
+
+    if [ "$extraenvimports" != "" ]; then
+      echo "Do you also want to import from $extraenvimports ?"
+      myread useenvimports y
+
+      if [ "$useenvimports" = "y" ]; then
+        envimports=$extraenvimports
+      fi
+    fi
+
+    echo "Enter any other import trees in search order"
+
+    import=wob
+    while [ "$import" != "" ]; do
+      myread import
+      intimports="$intimports $import"
+    done
+
+    imports="$exporttree $intimports $envimports $baseomnitree"
+  fi
+
+    firstimport=`echo $imports | awk '{print$1}'`
+
+
+#
+# Get the source trees
+#
+
+  echo
+  echo "Does this build tree have any source trees ?"
+  myread hassourcetree y
+
+  if [ "$hassourcetree" = "y" ]; then
+    echo
+    echo "Enter the source trees"
+    myread source $firstimport/src
+
+    sources=$source
+
+    while [ "$source" != "" ]; do
+      myread source
+      sources="$sources $source"
+    done
+  fi
+
+}
+
+
+###########################################################################
+#
+# Get default platform
+#
+
+getdefaultplatform() {
+  if [ -x /usr/local/bin/arch ]; then
+    defaultplatform=`/usr/local/bin/arch -binv`;
+    if [ ! -e "$baseomnitree/mk/platforms/$defaultplatform.mk" ]; then
+      unset defaultplatform
+    fi
+  fi
+}
+
+
+
+###########################################################################
+#
+# Check arguments
+#
+
+if [ $# -eq 0 ]; then
+
+  interactive
+
+else
+
+  while [ "$1" != "" ]; do
+    case "$1" in
+
+    -b)
+      shift
+      baseomnitree=$1
+      shift
+      ;;
+
+    -p)
+      shift
+      platform=$1
+      shift
+      ;;
+
+    -d)
+      shift
+      dest=$1
+      shift
+      ;;
+
+    -e)
+      shift
+      exporttree=$1
+      shift
+      ;;
+
+    -i)
+      shift
+      imports="$imports $1"
+      shift
+      ;;
+
+    -s)
+      shift
+      sources="$sources $1"
+      shift
+      ;;
+
+    *)
+      echo "usage: obuildtree [-b baseomnitree] [-p platform] [-d dest] [-e export]"
+      echo "                  [-i import]* [-s source]*"
+      exit 1
+      ;;
+
+    esac
+
+  done
+
+  #
+  # Fill in defaults not set on command line
+  #
+  
+  if [ "$baseomnitree" = "" ]; then
+    baseomnitree="$OMNI_TREE"
+    if [ "$baseomnitree" = "" ]; then
+      echo "Error: no base OMNI tree specified"
+      exit 1
+    fi
+  fi
+
+  if [ "$platform" = "" ]; then
+    getdefaultplatform
+    platform=$defaultplatform
+  fi
+
+  if [ "$dest" = "" ]; then
+    dest="$platform"
+  fi
+
+  imports="$exporttree $imports $baseomnitree"
+
 fi
 
-echo -n "> [$defaultplatform] "
 
-myread platform
 
-if [ "$platform" = "" ]; then
-  platform="$defaultplatform"
-fi
+###########################################################################
+#
+# A few sanity checks
+#
 
 if [ ! -r "$baseomnitree/mk/platforms/$platform.mk" ]; then
   echo
@@ -103,126 +309,58 @@ if [ ! -r "$baseomnitree/mk/platforms/$platform.mk" ]; then
   exit 1
 fi
 
-
-###########################################################################
-#
-# Get the destination
-#
-
-echo
-echo "Enter the destination directory"
-echo -n "> [$platform] "
-
-myread dest
-
-if [ "$dest" = "" ]; then
-  dest="$platform"
-fi
-
-
 if [ -e "$dest" ]; then
   echo "Error: \"$dest\" already exists."
   exit 1
 fi
 
 
+
 ###########################################################################
 #
-# Get the import trees
+# Tell the user what's going on
 #
 
 echo
-echo "Enter the import trees in search order (the base OMNI tree"
-echo "\"$baseomnitree\" will always be searched after these)"
-
-import=wob
-while [ "$import" != "" ]; do
-  echo -n "> "
-  myread import
-  if [ "$firstimport" = "" ]; then
-    firstimport="$import"
+echo "************************************************************************"
+echo
+echo "Creating OMNI build tree \"$dest\" for platform \"$platform\""
+echo
+if [ "$exporttree" != "" ]; then
+  echo "Export tree is $exporttree"
+else
+  echo "No export tree"
+fi
+echo
+echo "Import trees are:"
+for i in $imports; do
+  if [ -d $i ]; then
+    echo $i
+  else
+    echo "$i - DOESN'T EXIST"
   fi
-  imports="$imports $import"
-  revimports="$import $revimports"
 done
-
-if [ "$firstimport" = "" ]; then
-  firstimport="$baseomnitree"
-fi
-imports="$imports $baseomnitree"
-revimports="$baseomnitree $revimports"
-
-
-###########################################################################
-#
-# Get the export tree
-#
-
 echo
-echo "Does this build tree have an export tree ?"
-echo -n "> [n] "
-
-myread isexporttree
-
-if [ "$isexporttree" = "" ]; then
-  isexporttree="n"
-fi
-
-if [ "$isexporttree" = "y" ]; then
-  echo
-  echo "Enter the export tree"
-  echo -n "> [$firstimport] "
-
-  myread exporttree
-
-  if [ "$exporttree" = "" ]; then
-    exporttree="$firstimport"
-  fi
-fi
-
-
-###########################################################################
-#
-# Get the source trees
-#
-
-echo
-echo "Does this build tree have any source trees ?"
-echo -n "> [n] "
-
-myread issourcetree
-
-if [ "$issourcetree" = "" ]; then
-  issourcetree="n"
-fi
-
-if [ "$issourcetree" = "y" ]; then
-  echo
-  echo "Enter the source trees"
-  echo -n "> [$firstimport/src] "
-
-  myread source
-  if [ "$source" = "" ]; then
-    source="$firstimport/src"
-  fi
-  sources="$source"
-
-  while [ "$source" != "" ]; do
-    echo -n "> "
-    myread source
-    sources="$sources $source"
+if [ "$sources" != "" ]; then
+  echo "Source trees are:"
+  for s in $sources; do
+    if [ -d $s ]; then
+      echo $s
+    else
+      echo "$s - DOESN'T EXIST"
+    fi
   done
+else
+  echo "No source trees"
 fi
+echo
+
 
 
 ###########################################################################
 #
 # Create the destination directory and its config directory
 #
-
-echo
-echo "Creating OMNI build tree \"$dest\" for platform \"$platform\""
-echo
 
 set -e
 
@@ -261,6 +399,10 @@ EOF
 # same directory.  Note that the order is the reverse of the search order
 # (because later .mk files can override variable settings in previous ones).
 #
+
+for i in $imports; do
+  revimports="$i $revimports"
+done
 
 for i in $revimports; do
 
